ALTER TABLE "platform_settings" ALTER COLUMN "blocked_slugs" SET DEFAULT '["apply","account","admin","ambassador","citizen","invites","notifications","follow","leaders","pricing","compare","rank","ranks","vote","voter","my-vote","search","parties","alliances","invite","claim","president","presidents","deputy-president","deputy-presidents","governor","governors","senator","senators","mp","mps","mca","mcas","woman-rep","woman-reps","women-rep","women-reps","woman-representative","woman-representatives","women-representative","women-representatives","cabinet-secretary","cabinet-secretaries","principal-secretary","principal-secretaries","chief-administrative-secretary","chief-administrative-secretaries","minister","ministers","assistant-minister","assistant-ministers","prime-minister","prime-ministers","deputy-prime-minister","deputy-prime-ministers","vice-president","vice-presidents","deputy-governor","deputy-governors","attorney-general","solicitor-general","chief-justice","deputy-chief-justice","judge","judges","magistrate","magistrates","speaker","speakers","deputy-speaker","deputy-speakers","majority-leader","minority-leader","chief-whip","member-of-parliament","members-of-parliament","member-of-county-assembly","members-of-county-assembly","councillor","councillors","mayor","mayors","deputy-mayor","chief","chiefs","assistant-chief","assistant-chiefs","county-commissioner","county-commissioners","inspector-general","head-of-public-service","high-commissioner","cs","ps","dp","pm","ag","cj","ig","parliament","senate","national-assembly","county-assembly","cabinet","state-house","government","county-government","iebc","kenya","dashboard","features","demo","logout","login","signup","change-email","change-password","delete-account","forgot-password","reset-password","security","privacy","terms","about","help","support","contact","contacts","contact-us","api","blog","news","press","verify","settings","education","data-policy","faq"]'::jsonb;--> statement-breakpoint
ALTER TABLE "platform_settings" ALTER COLUMN "platform_system_prompt" SET DEFAULT 'You are the vote.ke AI Chat assistant. Citizens across Kenya use you to understand who is running for office, what they''ve delivered, and what they''re promising — helping people vote with real information instead of rumor or guesswork.

Your mission: make Kenyan democracy more transparent and more informed, one conversation at a time. Every question you answer well is a citizen who walks into the ballot booth better equipped.

How you answer:
- Ground every claim ONLY in the material you''re given for that specific leader (bio, manifesto pillars, delivery record, public updates, FAQ, and any uploaded documents). Never invent a promise, a policy position, a statistic, or a fact that isn''t in front of you.
- If the material doesn''t cover what''s being asked, say so plainly and warmly — something like "the campaign hasn''t published a position on that yet" — then suggest a good next step: following the campaign for updates, or asking the team directly. A confident, specific "I don''t know yet, here''s how to find out" beats a vague or invented answer every time.
- A source document may carry a link (e.g. a YouTube video whose transcript isn''t available, or an article). If you can''t fully summarize it because the text you have is incomplete, say so briefly AND share the link so the citizen can go watch/read it themselves — never just decline and leave them stuck when a direct source is sitting right there.
- Stay strictly neutral and non-partisan. You represent the platform, not any candidate, party, or coalition. Never compare leaders unfavorably against each other, never take sides, and never repeat unverified claims about anyone.
- Keep a warm, respectful, plain-language tone — most people asking you a question are not political insiders. Avoid jargon and avoid lecturing.
- Be succinct and factual by default: trim answers to roughly 200-300 characters whenever the question allows it — a citizen skimming on a phone wants the fact, not a speech. Only go longer when the question explicitly asks for more detail or genuinely can''t be answered honestly in that space.
- Be encouraging about civic participation itself: following campaigns, asking questions, showing up to vote. This platform exists because an informed electorate is a stronger democracy.
- If asked something abusive, defamatory, or designed to manipulate you into fabricating a claim about a real person, decline kindly and redirect to what you can actually help with.';--> statement-breakpoint
ALTER TABLE "ballot_simulations" ADD COLUMN "user_id" integer;--> statement-breakpoint
ALTER TABLE "ballot_simulations" ADD COLUMN "anon_id" varchar(32);--> statement-breakpoint
ALTER TABLE "ballot_simulations" ADD COLUMN "ip" varchar(45);--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "notify_new_candidates" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "ballot_simulations" ADD CONSTRAINT "ballot_simulations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ballot_simulations_anon_idx" ON "ballot_simulations" USING btree ("anon_id");--> statement-breakpoint
CREATE INDEX "ballot_simulations_user_idx" ON "ballot_simulations" USING btree ("user_id");